<a href="https://colab.research.google.com/github/arlspt/Machine_Learning/blob/main/Pertemuan1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Nama: Muhammad Ariel Saputra**<br>
**NIM: 2241720034**<br>
**Kelas: TI-3D**

# **Job Sheet 1.1: Ekstrasi Fitur**

# 1. Implementasi Normalisasi

In [ ]:
def norm_data(data) :
  # Melakukan normalisasi data.
  # Parameters:
  # data (list): Data yang akan dinormalisasi.
  # Returns:
  # data (list): Data yang sudah dinormalisasi.

  data_max = max(data)
  data_min = min(data)
  data_len = len(data)

  for i in range(0, data_len) :
    data[i] = (data[i] - data_min) / (data_max - data_min)
  return data

# Contoh penggunaan
data = [10, 11, 12, 14, 16]
n_data = norm_data(data)
print(n_data)

[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

np.set_printoptions(precision=6)
np.set_printoptions(suppress=True)

data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

data = np.asarray(data)
print("Data Asli")
print(data)

scaler = MinMaxScaler()
scaled = scaler.fit_transform(data)
print("Data Normalisasi")
print(scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


# 2. Implementasi Standarisasi

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

np.set_printoptions(precision=6)
np.set_printoptions(suppress=True)

data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

data = np.asarray(data)
print("Data Asli")
print(data)

scaler = StandardScaler()
scaled = scaler.fit_transform(data)
print("Data Normalisasi")
print(scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi
[[ 1.358732 -0.76956 ]
 [-0.339683  1.412317]
 [-1.019049 -0.642757]]


# 3. Implementasi Ordinal Encoding

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

transform_oe = oe.fit_transform(data)

print("Data Asli")
print(data)

print("Data Transformasi Ordinal Encoder")
print(transform_oe)

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[2.]
 [0.]
 [1.]
 [3.]]


# 4. Implementasi One-Hot Encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

transform_ohe = ohe.fit_transform(data)

print("Data Asli")
print(data)

print("Data Transformasi Ordinal Encoder")
print(transform_ohe.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


# 5. Implementasi Dummy Variable Encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder

de = OneHotEncoder(drop='first')

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

transform_de = de.fit_transform(data)

print("Data Asli")
print(data)

print("Data Transformasi Ordinal Encoder")
print(transform_de.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


# 6. Studi Kasus Ekstrasi Fitur dari Data Teks

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

corspus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story']

vect = TfidfVectorizer(stop_words='english')
resp = vect.fit_transform(corspus)

print('Hasil Token')
print(vect.get_feature_names_out())

Hasil Token
['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']


# Tugas Praktikum

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

file_path = '/content/drive/MyDrive/corpus.txt'
with open(file_path, 'r') as file:
    corpus = file.readlines()

# Membuat objek TfidfVectorizer
vectorizer = TfidfVectorizer()

# Mengubah teks menjadi matriks TF-IDF
X = vectorizer.fit_transform(corpus)

# Menampilkan fitur (kata-kata unik) dan hasil TF-IDF
print("Fitur (Kata-kata Unik):\n", vectorizer.get_feature_names_out())
print("\nMatriks TF-IDF:\n", X.toarray())


Fitur (Kata-kata Unik):
 ['ate' 'away' 'cat' 'corspus' 'end' 'finally' 'from' 'had' 'house'
 'little' 'mouse' 'of' 'ran' 'saw' 'story' 'the' 'tiny']

Matriks TF-IDF:
 [[0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.48385387 0.40164027 0.48385387 0.26109518 0.
  0.         0.         0.         0.26109518 0.48385387]
 [0.         0.         0.46807439 0.         0.         0.
  0.         0.         0.         0.         0.30428216 0.
  0.         0.5638867  0.         0.60856431 0.        ]
 [0.         0.44086807 0.         0.         0.         0.
  0.44086807 0.         0.36595836 0.         0.23789936 0.
  0.44086807 0.         0.         0.47579872 0.        ]
 [0.49117854 0.         0.40772037 0.         0.         0.49117854
  0.         0.         0.         0.         0.26504

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive
